import Head from 'next/head';
import Game from '../components/Game';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rock Paper Scissors</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Game />
    </div>
  );
}
