import Head from 'next/head';
import { useState } from 'react';
import Game from '../components/Game';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Choice from '../components/Choice';
import Router, { useRouter } from 'next/router';

export default function Home() {
  const [myChoice, setMyChoice] = useState('');
  const [score, setScore] = useState(0);

  return (
    <div>
      <Head>
        <title>Rock Paper Scissors</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header score={score} />
      {myChoice ? (
        <Choice
          myChoice={myChoice}
          setScore={setScore}
          score={score}
          setMyChoice={setMyChoice}
        />
      ) : (
        <Game setMyChoice={setMyChoice} />
      )}
      <Footer />
    </div>
  );
}
